const projectDetails = [
    {
        projectNumber: 1,
        projectName: 'Team Project - Meal Recipe Generator',
        description: 'An app to help generate meal ideas based on user inputs of dish type, meal type cook time and even ingredients',
        image: './assets/images/Meal-Generator.png',
        altText: 'AltText',
        titleText: 'Title Text',
        gitHubLink: 'https://github.com/garrettWinter/meal-recipe-generator',
        deployedLink: 'https://garrettwinter.github.io/meal-recipe-generator/',
    },
    {
        projectName: "Team Project - Sal's Online Movie Store",
        description: 'tbd',
        image: 'tbd',
        altText: 'tbd',
        titleText: 'tbd',
        gitHubLink: 'tbd',
        deployedLink: 'tbd',
    },
    // {
    //     projectName: 'Indivdual Project - ',
    //     description: 'tbd',
    //     image: 'tbd',
    //     altText: 'tbd',
    //     titleText: 'tbd',
    //     gitHubLink: 'tbd',
    //     deployedLink: 'tbd',
    // },
    // {
    //     projectName: 'Indivdual Project - ',
    //     description: 'tbd',
    //     image: 'tbd',
    //     altText: 'tbd',
    //     titleText: 'tbd',
    //     gitHubLink: 'tbd',
    //     deployedLink: 'tbd',
    // },
    // {
    //     projectName: 'Indivdual Project - ',
    //     description: 'tbd',
    //     image: 'tbd',
    //     altText: 'tbd',
    //     titleText: 'tbd',
    //     gitHubLink: 'tbd',
    //     deployedLink: 'tbd',
    // },
    // {
    //     projectName: 'Indivdual Project - ',
    //     description: 'tbd',
    //     image: 'tbd',
    //     altText: 'tbd',
    //     titleText: 'tbd',
    //     gitHubLink: 'tbd',
    //     deployedLink: 'tbd',
    // },
]

export default projectDetails;