const projectDetails = [
    {
        projectName: 'Team Project - TaskMaster',
        description: 'A MERN stack todo application to create lists of tasks and subtasks.',
        image: 'assets/images/TaskMaster-Homepage.png',
        altText: 'An image show casing the Team Project - TaskMaster',
        titleText: 'Team Project - TaskMaster',
        gitHubLink: 'https://github.com/Wir3s/taskmaster',
        deployedLink: 'https://sal-task-master.herokuapp.com/',
    },
    {
        projectName: 'Team Project - Meal Recipe Generator',
        description: 'A Github deployed app to help generate meal ideas based on user inputs of dish type, meal type cook time and even ingredients',
        image: 'assets/images/Meal-Generator.png',
        altText: 'An image show casing the Team Project - Meal Recipe Generator',
        titleText: 'Team Project - Meal Recipe Generator',
        gitHubLink: 'https://github.com/garrettWinter/meal-recipe-generator/',
        deployedLink: 'https://garrettwinter.github.io/meal-recipe-generator/',
    },
    {
        projectName: "Team Project - Sal's Online Movie Store",
        description: 'A Heroku deployed app to mock a online store to purchase movies that allows users to create accounts, add products to shopping cart, checkout and view order history.',
        image: 'assets/images/Online-Movie-Store-Homepage.png',
        altText: "An image show casing the Team Project - Sal's Online Movie Store",
        titleText: "Team Project - Sal's Online Movie Store",
        gitHubLink: 'https://github.com/garrettWinter/online-movie-store',
        deployedLink: 'https://sals-online-movies.herokuapp.com/',
    },
    {
        projectName: "Indivdual Project - Winter's Weather Dashboard",
        description: 'A Github deployed app that allows the user to look up 5 day forecasts by entering a city. It will save your searched cities locally for ease of use.',
        image: 'assets/images/Winters-Weather-Dashboard.png',
        altText: "An image show casing the Indivdual Project - Winter's Weather Dashboard",
        titleText: "Indivdual Project - Winter's Weather Dashboard",
        gitHubLink: 'https://github.com/garrettWinter/winters-weather-dashboard/',
        deployedLink: 'https://garrettwinter.github.io/winters-weather-dashboard/',
    },
    {
        projectName: "Indivdual Project - Garrett's Todo List",
        description: 'A Heroku deployed app to that allows users to be able to keep track of notes and tasks online. Data is stored online to allow the user store and access notes from any device.',
        image: 'assets/images/Todo-Tracker.png',
        altText: "An image show casing the Indivdual Project - Garrett's Todo List",
        titleText: "Indivdual Project - Garrett's Todo List",
        gitHubLink: 'https://github.com/garrettWinter/garretts-todo-list/',
        deployedLink: 'https://rocky-retreat-01110.herokuapp.com/',
    },
    {
        projectName: "Indivdual Project - Winter's Blogs",
        description: 'A Heroku deployed app that allows users create accounts and then to be able to create posts and add comments to others posts.',
        image: 'assets/images/Blogs-Homepage.png',
        altText: "An image show casing the Indivdual Project - Winter's Blogs",
        titleText: "Indivdual Project - Winter's Blogs",
        gitHubLink: 'https://github.com/garrettWinter/winters-blogs/',
        deployedLink: 'https://winters-blogs.herokuapp.com/',
    },
    {
        projectName: 'Indivdual Project - Javascript Code Quiz',
        description: 'A Github deployed app to quiz users with 10 questions about basic Javascript. A score is calculated based on the number of right questions and time remaining.',
        image: 'assets/images/JavaScript-Code-Quiz.png',
        altText: 'An image show casing the Indivdual Project - Javascript Code Quiz',
        titleText: 'Indivdual Project - Javascript Code Quiz',
        gitHubLink: 'https://github.com/garrettWinter/javascript-code-quiz/',
        deployedLink: 'https://garrettwinter.github.io/javascript-password-generator-build/',
    },
]

export default projectDetails;